Spring:
  application:
    name: store
  datasource:
    url: ${DATASOURCE_URL}
  jpa:
    show-sql: true
  jwt:
    secret: GEoCe6iMrEi8yYI1osz6zdZRxEFwoMkcMSO1eH8KRums2EnC9XqzpHUxee86bwd0QeGz4mkjjgxu7JRNenm/dg==
    refreshTokenExpiration: 420
    accessTokenExpiration: 300
    jwtBlacklistprefix: jwt:blacklist-
  redis:
    datasource:
      url: ${REDIS_URL}
